# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vivado_Projects/i2c_wrapper/i2c_wrapper/i2c_wrapper.srcs/sources_1/ip/rom_data/rom_data.xci
# IP: The module: 'rom_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado_Projects/i2c_wrapper/i2c_wrapper/i2c_wrapper.srcs/sources_1/ip/rom_data/rom_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_data'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Vivado_Projects/i2c_wrapper/i2c_wrapper/i2c_wrapper.srcs/sources_1/ip/rom_data/rom_data.xci
# IP: The module: 'rom_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado_Projects/i2c_wrapper/i2c_wrapper/i2c_wrapper.srcs/sources_1/ip/rom_data/rom_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
